// GENERATED by tools/config-page.mts — DO NOT EDIT.
// Regenerate with:  node tools/config-page.mts <this dir>/config-schema.mts
//
// The SAME schema emits config-page.html, so the page's keys/types and the
// watch-side type below cannot drift. Pass WEATHER_CONFIG_DEFAULTS as useConfig's
// `initial` and a watch that has never been configured agrees, key for key,
// with a page the wearer has never opened.
//
//   import { useConfig } from "runtime/config";
//   import { type WeatherConfig, WEATHER_CONFIG_DEFAULTS } from "./config-types";
//   const cfg = useConfig<WeatherConfig>(WEATHER_CONFIG_DEFAULTS);

/** Settings written by config-page.html and merged by `useConfig`. */
export interface WeatherConfig {
	/** City (text) */
	city: string;
	/** Units (select) */
	units: "metric" | "imperial";
	/** Accent colour (color) */
	accent: string;
}

/** The page's own defaults — the value `useConfig` seeds with before the first save. */
export const WEATHER_CONFIG_DEFAULTS: WeatherConfig = {
	city: "Berlin",
	units: "metric",
	accent: "#ffaa55",
};
