// PURE submodule (preload-eligible) with REAL weight: a ~4KB const string
// table + pure derivation functions. No module-scope side effects, no host
// construction, no reactive state — so under PRELOAD_PURE this entire module
// freezes into the mod archive (ROM) at build time. All-in-main, the same
// bytes sit in heap-resident main.js and sink the boot (measured — that is
// this example's whole point).
export const STATIONS = [
	"alpha station 000 — sector A0 relay uplink",
	"bravo station 001 — sector B1 relay uplink",
	"charlie station 002 — sector C2 relay uplink",
	"delta station 003 — sector D3 relay uplink",
	"echo station 004 — sector E4 relay uplink",
	"foxtrot station 005 — sector F5 relay uplink",
	"golf station 006 — sector G6 relay uplink",
	"hotel station 007 — sector A7 relay uplink",
	"india station 008 — sector B8 relay uplink",
	"juliett station 009 — sector C0 relay uplink",
	"kilo station 010 — sector D1 relay uplink",
	"lima station 011 — sector E2 relay uplink",
	"mike station 012 — sector F3 relay uplink",
	"november station 013 — sector G4 relay uplink",
	"oscar station 014 — sector A5 relay uplink",
	"papa station 015 — sector B6 relay uplink",
	"quebec station 016 — sector C7 relay uplink",
	"romeo station 017 — sector D8 relay uplink",
	"sierra station 018 — sector E0 relay uplink",
	"tango station 019 — sector F1 relay uplink",
	"uniform station 020 — sector G2 relay uplink",
	"victor station 021 — sector A3 relay uplink",
	"whiskey station 022 — sector B4 relay uplink",
	"xray station 023 — sector C5 relay uplink",
	"yankee station 024 — sector D6 relay uplink",
	"zulu station 025 — sector E7 relay uplink",
	"alpha station 026 — sector F8 relay uplink",
	"bravo station 027 — sector G0 relay uplink",
	"charlie station 028 — sector A1 relay uplink",
	"delta station 029 — sector B2 relay uplink",
	"echo station 030 — sector C3 relay uplink",
	"foxtrot station 031 — sector D4 relay uplink",
	"golf station 032 — sector E5 relay uplink",
	"hotel station 033 — sector F6 relay uplink",
	"india station 034 — sector G7 relay uplink",
	"juliett station 035 — sector A8 relay uplink",
	"kilo station 036 — sector B0 relay uplink",
	"lima station 037 — sector C1 relay uplink",
	"mike station 038 — sector D2 relay uplink",
	"november station 039 — sector E3 relay uplink",
	"oscar station 040 — sector F4 relay uplink",
	"papa station 041 — sector G5 relay uplink",
	"quebec station 042 — sector A6 relay uplink",
	"romeo station 043 — sector B7 relay uplink",
	"sierra station 044 — sector C8 relay uplink",
	"tango station 045 — sector D0 relay uplink",
	"uniform station 046 — sector E1 relay uplink",
	"victor station 047 — sector F2 relay uplink",
	"whiskey station 048 — sector G3 relay uplink",
	"xray station 049 — sector A4 relay uplink",
	"yankee station 050 — sector B5 relay uplink",
	"zulu station 051 — sector C6 relay uplink",
	"alpha station 052 — sector D7 relay uplink",
	"bravo station 053 — sector E8 relay uplink",
	"charlie station 054 — sector F0 relay uplink",
	"delta station 055 — sector G1 relay uplink",
	"echo station 056 — sector A2 relay uplink",
	"foxtrot station 057 — sector B3 relay uplink",
	"golf station 058 — sector C4 relay uplink",
	"hotel station 059 — sector D5 relay uplink",
	"india station 060 — sector E6 relay uplink",
	"juliett station 061 — sector F7 relay uplink",
	"kilo station 062 — sector G8 relay uplink",
	"lima station 063 — sector A0 relay uplink",
	"mike station 064 — sector B1 relay uplink",
	"november station 065 — sector C2 relay uplink",
	"oscar station 066 — sector D3 relay uplink",
	"papa station 067 — sector E4 relay uplink",
	"quebec station 068 — sector F5 relay uplink",
	"romeo station 069 — sector G6 relay uplink",
	"sierra station 070 — sector A7 relay uplink",
	"tango station 071 — sector B8 relay uplink",
	"uniform station 072 — sector C0 relay uplink",
	"victor station 073 — sector D1 relay uplink",
	"whiskey station 074 — sector E2 relay uplink",
	"xray station 075 — sector F3 relay uplink",
	"yankee station 076 — sector G4 relay uplink",
	"zulu station 077 — sector A5 relay uplink",
	"alpha station 078 — sector B6 relay uplink",
	"bravo station 079 — sector C7 relay uplink",
	"charlie station 080 — sector D8 relay uplink",
	"delta station 081 — sector E0 relay uplink",
	"echo station 082 — sector F1 relay uplink",
	"foxtrot station 083 — sector G2 relay uplink",
	"golf station 084 — sector A3 relay uplink",
	"hotel station 085 — sector B4 relay uplink",
	"india station 086 — sector C5 relay uplink",
	"juliett station 087 — sector D6 relay uplink",
	"kilo station 088 — sector E7 relay uplink",
	"lima station 089 — sector F8 relay uplink",
	"mike station 090 — sector G0 relay uplink",
	"november station 091 — sector A1 relay uplink",
	"oscar station 092 — sector B2 relay uplink",
	"papa station 093 — sector C3 relay uplink",
	"quebec station 094 — sector D4 relay uplink",
	"romeo station 095 — sector E5 relay uplink",
	"sierra station 096 — sector F6 relay uplink",
	"tango station 097 — sector G7 relay uplink",
	"uniform station 098 — sector A8 relay uplink",
	"victor station 099 — sector B0 relay uplink",
];

export function detail(i: number): string {
	return STATIONS[i % STATIONS.length];
}
