// GENERATED by tools/gen-boot-probe.mts --bytes 0 — do not edit.
// PURE module: const table + pure derivation only, so --preload-pure can
// freeze it into the mod archive; without the flag it bundles into main.js.
export const TABLE = [

];
export const pick = (i: number) => (TABLE.length ? TABLE[i % TABLE.length] : "empty #" + i);
