// GENERATED by tools/gen-boot-probe.mts --bytes 0 --empty 0 — do not edit.
// v1.5 boot-cost matrix probe: the navmany skeleton (2 labels, Navigator,
// ticking signal — the measured BOOTING baseline) + a parameterized pure
// data module. Build --app probe (all-in-main) vs --app probe --preload-pure
// (data frozen to ROM) and compare boot verdicts at equal --bytes.
import { render } from "runtime/jsx-runtime";
import { Navigator } from "runtime/flow";
import { useState } from "runtime/signals";
import { pick } from "./probe/data";

const bg = new Skin({ fill: "black" });
const big = new Style({ font: "bold 28px Gothic", color: "white" });
const small = new Style({ font: "18px Gothic", color: "#AAAAAA" });

let NAV: any = null;
const [pings, setPings] = useState(0);
setInterval(() => setPings((p: number) => p + 1), 1000);

const screen = (i: number) => () => (
	<Column>
		<Label style={big} string={"Probe #" + i} />
		<Label style={small} string={() => pick(pings())} />
	</Column>
);

// burn K fresh runtime keys (each distinct dynamic property name interns one)
const burn: any = {};
for (let i = 0; i < 0; i++) burn["zk" + i] = i;

render(() => (
	<Container left={0} right={0} top={0} bottom={0} focus={true}
		onPressSelect={() => { if (NAV) NAV.push(screen(NAV.depth() + 1)); }}
		onPressBack={() => { if (NAV && NAV.canPop()) { NAV.pop(); return true; } return false; }}>
		<Column>
			<Navigator root={(nav: any) => { NAV = nav; return screen(1)(); }} />
		</Column>
	</Container>
), { skin: bg, style: small });
