// Static preview SITE builder — the zero-install, click-and-see shop window.
// CloudPebble tier 2 (tools/preview.mts) already runs the SHIPPED runtime in a
// browser, but it is one app per invocation and needs a checkout + `pnpm run
// preview`. The competitors people actually click (strata, pebbleface-studio)
// are a URL; we were not. This wraps the SAME builder into a Pages-servable
// gallery: one `index.html` hosting N preview pages in iframes, with a
// gabbro/emery shape toggle that just re-points each frame at the `?shape=`
// the preview page already understands (no new preview machinery).
//
// The output under site/ is COMMITTED — GitHub Pages serves a branch path
// as-is, so the generated bytes ARE the deploy artifact (site/README.md has
// the one-time setup). Regenerate after touching an example or the runtime:
//   node tools/build-site.mts
//
// APPS is a curated list, not "every example": each entry must RENDER under
// the DOM stubs (tools/preview/piu-dom.js). Verified 2026-07 by loading each
// generated bundle under a Node DOM shim — anything reaching the Canvas Port
// (`node.invalidate is not a function`) or the host `watch` clock global
// (`watch is not defined`) is NOT stub-backed today, which is why the
// draw-based `ultraface` and the phone-data `weather` face are absent. Adding
// them means growing piu-dom.js first, not this list.
import { execFileSync } from "node:child_process";
import { cpSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..");
const SITE = join(ROOT, "site");
const PREVIEW = join(ROOT, "tools/preview.mts");

interface Entry {
	/** example name under src/tsx/examples — also the site/apps/<app>/ dir */
	app: string;
	/** card heading in the gallery */
	title: string;
	/** one sentence: what the reader should watch for once they drive it */
	blurb: string;
}

const APPS: Entry[] = [
	{
		app: "pulse",
		title: "pulse — the flagship face",
		blurb:
			"A live clock, a per-second pulse dot, and three accent themes on up/down (persisted to flash). The one composition that runs every proven mechanism at real arena pressure.",
	},
	{
		app: "counter",
		title: "counter — the classic",
		blurb:
			"up = +1, down = -1. One useState, one bound Label, and no VDOM diff anywhere: the signal writes the Label's string directly.",
	},
	{
		app: "menu",
		title: "menu — a driven list",
		blurb:
			"The app owns the selected index; Menu highlights that row and scrolls to keep it inside the viewport. up/down wrap.",
	},
	{
		app: "sectionlist",
		title: "sectionlist — grouped rows",
		blurb:
			"Three sections in one recycled five-slot window. Headers are never selectable, so stepping walks row-to-row ACROSS sections and the list scrolls past each boundary.",
	},
	{
		app: "card",
		title: "card — a reactive title bar",
		blurb:
			"Two titled boxes. The second card's title is a thunk, so up/down repaint the title bar with zero bind wiring at the call site.",
	},
];

// The import map the preview just wrote is the AUTHORITY on which runtime
// modules the page can load — copy exactly those, not the whole build/preview/
// <app>/ directory. That dir is a scratch mount every earlier `pnpm run
// preview` also wrote into, so a plain recursive copy shipped runtime modules
// the current closure no longer needs (measured: a stale runtime/flow.js rode
// into counter/ and sectionlist/). Nothing here deletes: if a future closure
// SHRINKS, the orphan under site/apps/<app>/runtime/ shows up in `git status`
// at regen time and is removed by hand.
const importMap = (html: string): Record<string, string> => {
	const m = /<script type="importmap">([\s\S]*?)<\/script>/.exec(html);
	if (!m) throw new Error("build-site: preview page has no import map");
	return (JSON.parse(m[1]) as { imports: Record<string, string> }).imports;
};

mkdirSync(join(SITE, "apps"), { recursive: true });
for (const { app } of APPS) {
	// Shell out to the preview builder rather than importing it: preview.mts is
	// an argv script (top-level process.exit), and one process per app keeps its
	// esbuild + closure derivation exactly as `pnpm run preview` runs them.
	execFileSync(process.execPath, [PREVIEW, app], { cwd: ROOT, stdio: "inherit" });
	const from = join(ROOT, "build/preview", app);
	const to = join(SITE, "apps", app);
	const html = readFileSync(join(from, "index.html"), "utf8");
	mkdirSync(join(to, "runtime"), { recursive: true });
	for (const f of ["index.html", "app.js", "piu-dom.js"]) cpSync(join(from, f), join(to, f));
	for (const rel of Object.values(importMap(html))) cpSync(join(from, rel), join(to, rel));
}

// Frames carry a real `src` in the MARKUP (not JS-assigned on load) so the
// gallery renders with scripting off and the committed HTML is assertable;
// the toggle only rewrites it.
const card = ({ app, title, blurb }: Entry): string => `  <section class="card">
   <h2>${title}</h2>
   <p>${blurb}</p>
   <iframe data-app="${app}" src="apps/${app}/index.html?shape=round"
    title="${app} preview" loading="lazy"></iframe>
  </section>`;

writeFileSync(
	join(SITE, "index.html"),
	`<!DOCTYPE html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>signal-piu — zero-install preview gallery</title>
<style>
 :root { color-scheme: dark; }
 body { margin: 0; background: #14141f; color: #e7e7f0; line-height: 1.5;
        font-family: system-ui, sans-serif; }
 header, main, footer { max-width: 1100px; margin: 0 auto; padding: 0 20px; }
 header { padding-top: 40px; }
 h1 { margin: 0; font-size: 32px; letter-spacing: -.5px; }
 .tag { color: #a9a9c0; max-width: 68ch; }
 .shape { display: flex; gap: 8px; flex-wrap: wrap; margin: 20px 0 8px; }
 .shape button { font: inherit; font-size: 14px; padding: 7px 14px; cursor: pointer;
                 color: #cfcfe4; background: #23233a; border: 1px solid #35355a;
                 border-radius: 999px; }
 .shape button.on { background: #55ffaa; border-color: #55ffaa; color: #11221a; }
 .keys { color: #7a7a95; font-size: 14px; margin-top: 0; }
 main { display: grid; gap: 24px; padding-top: 16px;
        grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); }
 .card { background: #1c1c2c; border: 1px solid #2c2c46; border-radius: 12px;
         padding: 16px; }
 .card h2 { margin: 0 0 6px; font-size: 17px; }
 .card p { margin: 0 0 12px; color: #a9a9c0; font-size: 14px; }
 iframe { display: block; width: 100%; height: 330px; border: 0; border-radius: 8px;
          background: #1a1a2e; }
 footer { color: #8a8aa5; font-size: 14px; padding: 32px 20px 56px; }
 footer h2 { font-size: 16px; color: #cfcfe4; }
 footer code { color: #cfcfe4; }
</style>
<header>
 <h1>signal-piu</h1>
 <p class="tag">Fine-grained reactive UI — Solid-style signals + JSX, no VDOM — for Pebble
 watches on Moddable XS/Piu. Every watch below is a REAL example running the SHIPPED runtime
 in your browser: no SDK, no emulator, no install.</p>
 <div class="shape" role="group" aria-label="watch shape">
  <button type="button" data-shape="round" class="on">gabbro &middot; round 260&times;260</button>
  <button type="button" data-shape="emery">emery &middot; rect 200&times;228</button>
 </div>
 <p class="keys">Click a watch to focus it, then drive it: &uarr; up &middot; &darr; down
 &middot; Enter select &middot; Backspace back.</p>
</header>
<main>
${APPS.map(card).join("\n")}
</main>
<footer>
 <h2>What this is not</h2>
 <p>Layout here is APPROXIMATE: Piu's layout engine is not reimplemented, only DOM-rendering
 stubs stand in for it. The preview bundles the raw <code>.tsx</code>, so the auto-thunk
 lowering pass never runs (bare reactive props stay static — these examples write thunks).
 Lazy modules (<code>importNow</code>), bitmaps, the Canvas Port and the host clock global are
 not stubbed, which is why the draw-based <code>ultraface</code> and the phone-data
 <code>weather</code> face are not in this gallery. QEMU stays the truth:
 <code>pnpm run dev -- --app pulse</code>.</p>
 <p>Regenerate this site with <code>node tools/build-site.mts</code> from
 <code>projects/signal-piu</code>.</p>
</footer>
<script>
 const frames = document.querySelectorAll("iframe[data-app]");
 const buttons = document.querySelectorAll("button[data-shape]");
 for (const b of buttons)
  b.addEventListener("click", () => {
   const shape = b.dataset.shape;
   // Re-point each frame at the ?shape= the preview page already reads; a
   // fresh src RELOADS the app, which is what re-running render() at the new
   // Application size needs (screen.width is read once, at mount).
   for (const f of frames) f.src = "apps/" + f.dataset.app + "/index.html?shape=" + shape;
   for (const other of buttons) other.classList.toggle("on", other === b);
  });
</script>
`,
);

console.log(`build-site: site/ regenerated — ${APPS.length} apps`);
console.log(`  apps: ${APPS.map((a) => a.app).join(", ")}`);
console.log("  serve it: python3 -m http.server -d site 8080");
