// Generator for the v1.5 boot-cost matrix probes (docs/roadmap.md, "Auto
// pure-module preload"). Emits src/tsx/examples/probe.tsx + probe/data.ts
// (+ probe/e<i>.ts) so each probe varies EXACTLY ONE variable against the
// navmany baseline:
//   --bytes N   payload size of the pure string table in ./probe/data
//               (same source measured all-in-main vs --preload-pure)
//   --empty K   number of extra EMPTY pure modules imported by the entry
//               (fixed per-module cost; use with --bytes 0)
//   --keys K    allocate K FRESH dynamic property names at boot — measures
//               the machine's REMAINING key budget (keys.initial=256,
//               incremental=0: the pool never grows; exhaustion = abort)
// The strings are distinct/deterministic (not compressible away by minify),
// so raw payload bytes ~= shipped bytes. Rebuild + install after generating:
//   node tools/gen-boot-probe.mts --bytes 1024
//   node build.mts --app probe [--preload-pure]
import { mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseArgs } from "node:util";
import { packageRoot } from "./pkg-root.mts";

const { values } = parseArgs({
	options: {
		bytes: { type: "string", default: "0" },
		empty: { type: "string", default: "0" },
		keys: { type: "string", default: "0" },
	},
});
const bytes = Number(values.bytes);
const empty = Number(values.empty);
const keys = Number(values.keys);

const root = packageRoot(import.meta.dirname);
const exDir = join(root, "src", "tsx", "examples");
const probeDir = join(exDir, "probe");
mkdirSync(probeDir, { recursive: true });
for (const f of readdirSync(probeDir)) rmSync(join(probeDir, f));

// ---- probe/data.ts: a pure const table of ~`bytes` payload bytes ----------
const rows: string[] = [];
let size = 0;
for (let i = 0; size < bytes; i++) {
	const s = `station ${String(i).padStart(4, "0")} — sector ${(i * 7) % 26} relay uplink beacon ${(i * 31) % 997}`;
	rows.push(`\t"${s}",`);
	size += s.length + 3; // + quotes and comma actually shipped
}
writeFileSync(
	join(probeDir, "data.ts"),
	`// GENERATED by tools/gen-boot-probe.mts --bytes ${bytes} — do not edit.
// PURE module: const table + pure derivation only, so --preload-pure can
// freeze it into the mod archive; without the flag it bundles into main.js.
export const TABLE = [
${rows.join("\n")}
];
export const pick = (i: number) => (TABLE.length ? TABLE[i % TABLE.length] : "empty #" + i);
`,
);

// ---- probe/e<i>.ts: empty pure modules (fixed per-module cost) ------------
for (let i = 1; i <= empty; i++)
	writeFileSync(
		join(probeDir, `e${i}.ts`),
		`// GENERATED by tools/gen-boot-probe.mts --empty ${empty} — do not edit.
export const E${i} = ${i};
`,
	);

// ---- probe.tsx: the navmany skeleton + the probe imports ------------------
const eImports = Array.from(
	{ length: empty },
	(_, k) => `import { E${k + 1} } from "./probe/e${k + 1}";`,
).join("\n");
const eSum = empty ? ` + ${Array.from({ length: empty }, (_, k) => `E${k + 1}`).join(" + ")}` : "";
writeFileSync(
	join(exDir, "probe.tsx"),
	`// GENERATED by tools/gen-boot-probe.mts --bytes ${bytes} --empty ${empty} — do not edit.
// v1.5 boot-cost matrix probe: the navmany skeleton (2 labels, Navigator,
// ticking signal — the measured BOOTING baseline) + a parameterized pure
// data module. Build --app probe (all-in-main) vs --app probe --preload-pure
// (data frozen to ROM) and compare boot verdicts at equal --bytes.
import { render } from "runtime/jsx-runtime";
import { Navigator } from "runtime/flow";
import { useState } from "runtime/signals";
import { pick } from "./probe/data";
${eImports}
const bg = new Skin({ fill: "black" });
const big = new Style({ font: "bold 28px Gothic", color: "white" });
const small = new Style({ font: "18px Gothic", color: "#AAAAAA" });

let NAV: any = null;
const [pings, setPings] = useState(0);
setInterval(() => setPings((p: number) => p + 1), 1000);

const screen = (i: number) => () => (
	<Column>
		<Label style={big} string={"Probe #" + i${eSum}} />
		<Label style={small} string={() => pick(pings())} />
	</Column>
);

// burn K fresh runtime keys (each distinct dynamic property name interns one)
const burn: any = {};
for (let i = 0; i < ${keys}; i++) burn["zk" + i] = i;

render(() => (
	<Container left={0} right={0} top={0} bottom={0} focus={true}
		onPressSelect={() => { if (NAV) NAV.push(screen(NAV.depth() + 1)); }}
		onPressBack={() => { if (NAV && NAV.canPop()) { NAV.pop(); return true; } return false; }}>
		<Column>
			<Navigator root={(nav: any) => { NAV = nav; return screen(1)(); }} />
		</Column>
	</Container>
), { skin: bg, style: small });
`,
);

console.log(`probe generated: bytes=${size} (asked ${bytes}), empty modules=${empty}`);
