// Generator for the v1.5 boot-cost matrix probes (docs/roadmap.md, "Auto
// pure-module preload"). Emits src/tsx/examples/probe.tsx + probe/data.ts
// (+ probe/e<i>.ts) so each probe varies EXACTLY ONE variable against the
// navmany baseline:
//   --bytes N   payload size of the pure string table in ./probe/data
//               (same source measured all-in-main vs --preload-pure)
//   --empty K   number of extra EMPTY pure modules imported by the entry
//               (fixed per-module cost; use with --bytes 0)
//   --keys K    allocate K FRESH dynamic property names at boot — measures
//               the machine's REMAINING key budget (keys.initial=256,
//               incremental=0: the pool never grows; exhaustion = abort)
//   --code N    ~N bytes of PURE HELPER CODE (distinct const arrow fns +
//               a dispatch table so nothing is DCE-able) in ./probe/data
//               instead of the string table — measures the cost of CODE
//               all-in-main vs frozen via --preload-pure (the smart-split
//               question: can helpers/classes/screens live in ROM?)
//   --diet      with --code: emit the helpers as INLINE arrows in the
//               dispatch array — ZERO top-level binding names. This is
//               what an ideal name-mangling smart-split pass would emit;
//               isolates the per-helper NAME-symbol cost.
//   --klass N   ~N bytes of methods on ONE `const C = class` (plus a
//               frozen instance-of-sorts dispatch) — measures the
//               per-METHOD property-symbol cost of class-style code.
//   --res       DATA-TO-RESOURCE variant (the v2 candidate): the SAME table
//               ships as ONE binary blob in the flash resource area, read in
//               place via Resource() + offset decode — no array structure,
//               no module, no symbols. (Prototype rides the .pdc manifest
//               route: gen-manifest bundles any referenced *.pdc file.)
// The strings are distinct/deterministic (not compressible away by minify),
// so raw payload bytes ~= shipped bytes. Rebuild + install after generating:
//   node tools/gen-boot-probe.mts --bytes 1024
//   node build.mts --app probe [--preload-pure]
import { mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseArgs } from "node:util";
import { packageRoot } from "./pkg-root.mts";

const { values } = parseArgs({
	options: {
		bytes: { type: "string", default: "0" },
		empty: { type: "string", default: "0" },
		keys: { type: "string", default: "0" },
		res: { type: "boolean", default: false },
		code: { type: "string", default: "0" },
		diet: { type: "boolean", default: false },
		fat: { type: "string", default: "0" },
		klass: { type: "string", default: "0" },
	},
});
const bytes = Number(values.bytes);
const empty = Number(values.empty);
const keys = Number(values.keys);
const res = values.res === true;
const code = Number(values.code);
const diet = values.diet === true;
const fat = Number(values.fat); // target bytes PER HELPER (0 = default ~90)
const klass = Number(values.klass);

const root = packageRoot(import.meta.dirname);
const exDir = join(root, "src", "tsx", "examples");
const probeDir = join(exDir, "probe");
mkdirSync(probeDir, { recursive: true });
for (const f of readdirSync(probeDir)) rmSync(join(probeDir, f));

// ---- --code: ~N bytes of pure helper FUNCTIONS (dispatch-retained) --------
if (code > 0) {
	const fns: string[] = [];
	let csize = 0;
	for (let k = 0; csize < code; k++) {
		// --fat N pads each body with a distinct long literal: SAME total bytes
		// across FEWER functions — separates per-function from per-byte cost
		const pad =
			fat > 90 ? `"${`p${k}x`.repeat(Math.ceil((fat - 90) / 4)).slice(0, fat - 90)}" + ` : "";
		const f = `const h${k} = (x: number): string => ${pad}"h${k}[" + ((x * ${7 + k} + ${13 + k * 3}) % ${97 + k}) + "]" + ((x ^ ${k * 5 + 1}) & ${63 + k});`;
		fns.push(f);
		csize += f.length;
	}
	const body = diet
		? `const H: ((x: number) => string)[] = [
${fns
	.map((f) => {
		// strip the binding: keep only the arrow expression (ideal mangler output)
		const arrow = f.slice(f.indexOf("(x: number)"), -1);
		return `\t${arrow},`;
	})
	.join("\n")}
];`
		: `${fns.join("\n")}
const H = [${fns.map((_, k) => `h${k}`).join(", ")}];`;
	writeFileSync(
		join(probeDir, "data.ts"),
		`// GENERATED by tools/gen-boot-probe.mts --code ${code}${diet ? " --diet" : ""} — do not edit.
// PURE module: ${fns.length} distinct helpers + dispatch (DCE-proof).
// ${diet ? "DIET form: inline arrows, ZERO top-level binding names — what an ideal name-mangling smart-split pass emits." : "NAMED form: const-arrow bindings (realistic hand-written code)."}
${body}
export const pick = (i: number): string => H[i % H.length](i);
`,
	);
	console.log(
		`probe generated (CODE${diet ? "+DIET" : ""} mode): ~${csize}B across ${fns.length} helpers`,
	);
} else if (klass > 0) {
	// ~N bytes of METHODS on one class expression (gotcha-13-safe const form).
	// Each method name is a distinct property symbol — the cost being measured.
	const ms: string[] = [];
	let ksize = 0;
	for (let k = 0; ksize < klass; k++) {
		const m = `\tm${k}(x: number): string { return "m${k}[" + ((x * ${7 + k} + ${13 + k * 3}) % ${97 + k}) + "]" + ((x ^ ${k * 5 + 1}) & ${63 + k}); }`;
		ms.push(m);
		ksize += m.length;
	}
	writeFileSync(
		join(probeDir, "data.ts"),
		`// GENERATED by tools/gen-boot-probe.mts --klass ${klass} — do not edit.
// PURE module: ONE class expression with ${ms.length} methods; per-method
// property symbols are the measured cost.
const C = class {
${ms.join("\n")}
};
const c = new C();
const M = [${ms.map((_, k) => `(x: number) => c.m${k}(x)`).join(", ")}];
export const pick = (i: number): string => M[i % M.length](i);
`,
	);
	console.log(`probe generated (KLASS mode): ~${ksize}B across ${ms.length} methods`);
} else {
	// ---- probe/data.ts: a pure const table of ~`bytes` payload bytes ----------
	const rows: string[] = [];
	let size = 0;
	for (let i = 0; size < bytes; i++) {
		const s = `station ${String(i).padStart(4, "0")} — sector ${(i * 7) % 26} relay uplink beacon ${(i * 31) % 997}`;
		rows.push(`\t"${s}",`);
		size += s.length + 3; // + quotes and comma actually shipped
	}
	writeFileSync(
		join(probeDir, "data.ts"),
		`// GENERATED by tools/gen-boot-probe.mts --bytes ${bytes} — do not edit.
// PURE module: const table + pure derivation only, so --preload-pure can
// freeze it into the mod archive; without the flag it bundles into main.js.
export const TABLE = [
${rows.join("\n")}
];
export const pick = (i: number) => (TABLE.length ? TABLE[i % TABLE.length] : "empty #" + i);
`,
	);
}

// ---- probe/e<i>.ts: empty pure modules (fixed per-module cost) ------------
for (let i = 1; i <= empty; i++)
	writeFileSync(
		join(probeDir, `e${i}.ts`),
		`// GENERATED by tools/gen-boot-probe.mts --empty ${empty} — do not edit.
export const E${i} = ${i};
`,
	);

// ---- --res: the same table as ONE binary blob in the resource area --------
// format: [u16le count][u16le cumulative END offset per entry][payload]
if (res) {
	const texts: string[] = [];
	let rsize = 0;
	for (let i = 0; rsize < bytes; i++) {
		const t = `station ${String(i).padStart(4, "0")} — sector ${(i * 7) % 26} relay uplink beacon ${(i * 31) % 997}`;
		texts.push(t);
		rsize += t.length + 3;
	}
	const payload = Buffer.from(texts.join(""), "latin1");
	const head = Buffer.alloc(2 + 2 * texts.length);
	head.writeUInt16LE(texts.length, 0);
	let end = 0;
	texts.forEach((t, k) => {
		end += t.length;
		head.writeUInt16LE(end, 2 + 2 * k);
	});
	mkdirSync(join(root, "assets"), { recursive: true });
	writeFileSync(join(root, "assets", "probe.pdc"), Buffer.concat([head, payload]));
	writeFileSync(
		join(exDir, "probe.tsx"),
		`// GENERATED by tools/gen-boot-probe.mts --bytes ${bytes} --res — do not edit.
// v2 candidate probe: the navmany skeleton + the SAME station table, but as
// ONE binary blob in the flash RESOURCE area (read IN PLACE via Resource();
// decode-on-read builds one transient string). No array structure, no extra
// module, no new symbols — only what a read touches costs arena, briefly.
import { render } from "runtime/jsx-runtime";
import { Navigator } from "runtime/flow";
import { useState } from "runtime/signals";

const bg = new Skin({ fill: "black" });
const big = new Style({ font: "bold 28px Gothic", color: "white" });
const small = new Style({ font: "18px Gothic", color: "#AAAAAA" });

// [u16le count][u16le cumulative end offsets][latin-1 payload]
// DEVICE-PROVEN access pattern (gabbro, 2026-07) — both naive forms DIE:
//   * new Uint8Array(resource) whole-blob wrap -> fxAbort memory full;
//   * String.fromCharCode.apply at render depth -> fxAbort JS stack
//     overflow (6KB stack; apply spreads one arg per byte).
// Use ranged resource.slice(a, b) copies (native, transient) and the
// Moddable String.fromArrayBuffer extension (host-verified symbol).
const r = new Resource("probe.pdc") as unknown as { slice(b: number, e: number): ArrayBuffer };
const u16 = (off: number): number => {
	const b = new Uint8Array(r.slice(off, off + 2));
	return b[0] | (b[1] << 8);
};
const count = u16(0);
const pick = (i: number): string => {
	if (!count) return "empty #" + i;
	const k = i % count;
	const s = k ? u16(2 * k) : 0;
	const e = u16(2 * k + 2);
	const base = 2 + 2 * count;
	return (String as unknown as { fromArrayBuffer(b: ArrayBuffer): string }).fromArrayBuffer(
		r.slice(base + s, base + e),
	);
};

let NAV: any = null;
const [pings, setPings] = useState(0);
setInterval(() => setPings((p: number) => p + 1), 1000);

const screen = (i: number) => () => (
	<Column>
		<Label style={big} string={"Probe #" + i} />
		<Label style={small} string={() => pick(pings())} />
	</Column>
);

render(() => (
	<Container left={0} right={0} top={0} bottom={0} focus={true}
		onPressSelect={() => { if (NAV) NAV.push(screen(NAV.depth() + 1)); }}
		onPressBack={() => { if (NAV && NAV.canPop()) { NAV.pop(); return true; } return false; }}>
		<Column>
			<Navigator root={(nav: any) => { NAV = nav; return screen(1)(); }} />
		</Column>
	</Container>
), { skin: bg, style: small });
`,
	);
	console.log(
		`probe generated (RES mode): payload=${payload.length}B entries=${texts.length} -> assets/probe.pdc`,
	);
	process.exit(0);
}

// ---- probe.tsx: the navmany skeleton + the probe imports ------------------
const eImports = Array.from(
	{ length: empty },
	(_, k) => `import { E${k + 1} } from "./probe/e${k + 1}";`,
).join("\n");
const eSum = empty ? ` + ${Array.from({ length: empty }, (_, k) => `E${k + 1}`).join(" + ")}` : "";
writeFileSync(
	join(exDir, "probe.tsx"),
	`// GENERATED by tools/gen-boot-probe.mts --bytes ${bytes} --empty ${empty} — do not edit.
// v1.5 boot-cost matrix probe: the navmany skeleton (2 labels, Navigator,
// ticking signal — the measured BOOTING baseline) + a parameterized pure
// data module. Build --app probe (all-in-main) vs --app probe --preload-pure
// (data frozen to ROM) and compare boot verdicts at equal --bytes.
import { render } from "runtime/jsx-runtime";
import { Navigator } from "runtime/flow";
import { useState } from "runtime/signals";
import { pick } from "./probe/data";
${eImports}
const bg = new Skin({ fill: "black" });
const big = new Style({ font: "bold 28px Gothic", color: "white" });
const small = new Style({ font: "18px Gothic", color: "#AAAAAA" });

let NAV: any = null;
const [pings, setPings] = useState(0);
setInterval(() => setPings((p: number) => p + 1), 1000);

const screen = (i: number) => () => (
	<Column>
		<Label style={big} string={"Probe #" + i${eSum}} />
		<Label style={small} string={() => pick(pings())} />
	</Column>
);

// burn K fresh runtime keys (each distinct dynamic property name interns one)
const burn: any = {};
for (let i = 0; i < ${keys}; i++) burn["zk" + i] = i;

render(() => (
	<Container left={0} right={0} top={0} bottom={0} focus={true}
		onPressSelect={() => { if (NAV) NAV.push(screen(NAV.depth() + 1)); }}
		onPressBack={() => { if (NAV && NAV.canPop()) { NAV.pop(); return true; } return false; }}>
		<Column>
			<Navigator root={(nav: any) => { NAV = nav; return screen(1)(); }} />
		</Column>
	</Container>
), { skin: bg, style: small });
`,
);

if (code === 0) console.log(`probe generated: bytes asked=${bytes}, empty modules=${empty}`);
